### ISSUE TITLE
change back to bash

### ISSUE THREAD

**Issue by diehard88** [theregoesmyeye/TermuxSetup#1]
I sucesfully ran the script and so far so good.

to restore bash, do I simply run the following:

 `chsh -s bash`

thanks.

**Comment by theregoesmyeye** [comment]
That's correct. Additionally,, 'chsh' is also an interactive program as well, so simply using 'chsh' will prompt you which shell to use at which point you could then type 'zsh', 'bash', or 'fish" (though you must download fish first if you want that one.)

**Comment by diehard88** [comment]
thanks.

is the VNC server persistent?
if you exit termux, does vnc remain in the background?

**Comment by theregoesmyeye** [comment]
VNC remains open until one of the following conditions:

1. You explicitly quit the VNC server.
2. You explicitly quit/force quit Termux.
3. The Termux notification disappears from your notification bar. If this
happens, Termux has likely shut down as well.
